### ISSUE TITLE
Need the ability to expire inidividual slides

### ISSUE THREAD

**Issue by jasonhwest** [Kings-Ridge-Christian-School/pieboard-server#11]

**Comment by lholliger** [comment]
slideshow as a whole expiration date has more importance than individual slide times. If a slide expire time were to be older than the slideshow, it would expire at the time the slideshow expires

**Comment by lholliger** [comment]
slideshow as a whole expiration date has more importance than individual slide times. If a slide expire time were to be older than the slideshow, it would expire at the time the slideshow expires

**Comment by lholliger** [comment]
fixed in #14
